{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyN5xcWLPaipfsE8MjKIs67B",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/shagunSrivastava9797-oss/CODSOFT_TASKSNO/blob/main/Contact_book.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import json\n",
        "import os\n",
        "\n",
        "FILE_NAME = \"contacts.json\"\n",
        "\n",
        "\n",
        "def load_contacts():\n",
        "    if os.path.exists(FILE_NAME):\n",
        "        with open(FILE_NAME, \"r\") as f:\n",
        "            return json.load(f)\n",
        "    return []\n",
        "\n",
        "\n",
        "def save_contacts(contacts):\n",
        "    with open(FILE_NAME, \"w\") as f:\n",
        "        json.dump(contacts, f, indent=4)\n",
        "\n",
        "\n",
        "def show_menu():\n",
        "    print(\"\\n===== CONTACT BOOK =====\")\n",
        "    print(\"1. Add a contact\")\n",
        "    print(\"2. View all contacts\")\n",
        "    print(\"3. Search contact\")\n",
        "    print(\"4. Update contact\")\n",
        "    print(\"5. Delete contact\")\n",
        "    print(\"6. Exit\")\n",
        "\n",
        "\n",
        "def add_contact(contacts):\n",
        "    name = input(\"Enter name: \").strip()\n",
        "    phone = input(\"Enter phone number: \").strip()\n",
        "    email = input(\"Enter email: \").strip()\n",
        "    address = input(\"Enter address: \").strip()\n",
        "\n",
        "    if not name or not phone:\n",
        "        print(\"Name and phone number are required.\")\n",
        "        return\n",
        "\n",
        "    contacts.append({\n",
        "        \"name\": name,\n",
        "        \"phone\": phone,\n",
        "        \"email\": email,\n",
        "        \"address\": address\n",
        "    })\n",
        "    save_contacts(contacts)\n",
        "    print(\"Contact added successfully!\")\n",
        "\n",
        "\n",
        "def view_contacts(contacts):\n",
        "    if not contacts:\n",
        "        print(\"\\nYour contact book is empty!\")\n",
        "        return\n",
        "    print(\"\\nYour Contacts:\")\n",
        "    for i, c in enumerate(contacts, start=1):\n",
        "        print(f\"{i}. {c['name']} - {c['phone']}\")\n",
        "\n",
        "\n",
        "def search_contact(contacts):\n",
        "    if not contacts:\n",
        "        print(\"\\nYour contact book is empty!\")\n",
        "        return\n",
        "    keyword = input(\"Enter name or phone number to search: \").strip().lower()\n",
        "    found = False\n",
        "    for c in contacts:\n",
        "        if keyword in c[\"name\"].lower() or keyword in c[\"phone\"]:\n",
        "            print(f\"\\nName: {c['name']}\")\n",
        "            print(f\"Phone: {c['phone']}\")\n",
        "            print(f\"Email: {c['email']}\")\n",
        "            print(f\"Address: {c['address']}\")\n",
        "            found = True\n",
        "    if not found:\n",
        "        print(\"No matching contact found.\")\n",
        "\n",
        "\n",
        "def update_contact(contacts):\n",
        "    view_contacts(contacts)\n",
        "    if not contacts:\n",
        "        return\n",
        "    try:\n",
        "        index = int(input(\"Enter contact number to update: \")) - 1\n",
        "        if 0 <= index < len(contacts):\n",
        "            print(\"Leave a field blank to keep it unchanged.\")\n",
        "            name = input(f\"New name ({contacts[index]['name']}): \").strip()\n",
        "            phone = input(f\"New phone ({contacts[index]['phone']}): \").strip()\n",
        "            email = input(f\"New email ({contacts[index]['email']}): \").strip()\n",
        "            address = input(f\"New address ({contacts[index]['address']}): \").strip()\n",
        "\n",
        "            if name:\n",
        "                contacts[index][\"name\"] = name\n",
        "            if phone:\n",
        "                contacts[index][\"phone\"] = phone\n",
        "            if email:\n",
        "                contacts[index][\"email\"] = email\n",
        "            if address:\n",
        "                contacts[index][\"address\"] = address\n",
        "\n",
        "            save_contacts(contacts)\n",
        "            print(\"Contact updated successfully!\")\n",
        "        else:\n",
        "            print(\"Invalid contact number.\")\n",
        "    except ValueError:\n",
        "        print(\"Please enter a valid number.\")\n",
        "\n",
        "\n",
        "def delete_contact(contacts):\n",
        "    view_contacts(contacts)\n",
        "    if not contacts:\n",
        "        return\n",
        "    try:\n",
        "        index = int(input(\"Enter contact number to delete: \")) - 1\n",
        "        if 0 <= index < len(contacts):\n",
        "            removed = contacts.pop(index)\n",
        "            save_contacts(contacts)\n",
        "            print(f\"Deleted contact: {removed['name']}\")\n",
        "        else:\n",
        "            print(\"Invalid contact number.\")\n",
        "    except ValueError:\n",
        "        print(\"Please enter a valid number.\")\n",
        "\n",
        "\n",
        "def main():\n",
        "    contacts = load_contacts()\n",
        "    while True:\n",
        "        show_menu()\n",
        "        choice = input(\"Choose an option (1-6): \").strip()\n",
        "\n",
        "        if choice == \"1\":\n",
        "            add_contact(contacts)\n",
        "        elif choice == \"2\":\n",
        "            view_contacts(contacts)\n",
        "        elif choice == \"3\":\n",
        "            search_contact(contacts)\n",
        "        elif choice == \"4\":\n",
        "            update_contact(contacts)\n",
        "        elif choice == \"5\":\n",
        "            delete_contact(contacts)\n",
        "        elif choice == \"6\":\n",
        "            print(\"Goodbye! Your contacts are saved.\")\n",
        "            break\n",
        "        else:\n",
        "            print(\"Invalid choice. Please select 1-6.\")\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ENtoR9ZpvMnQ",
        "outputId": "8fe26a6d-c4b3-4f23-8626-b922193f4d7a"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "===== CONTACT BOOK =====\n",
            "1. Add a contact\n",
            "2. View all contacts\n",
            "3. Search contact\n",
            "4. Update contact\n",
            "5. Delete contact\n",
            "6. Exit\n",
            "Choose an option (1-6): 1\n",
            "Enter name: Raghav \n",
            "Enter phone number: 456379876\n",
            "Enter email: Raghav876@gmail.com\n",
            "Enter address: Kali road, delhi\n",
            "Contact added successfully!\n",
            "\n",
            "===== CONTACT BOOK =====\n",
            "1. Add a contact\n",
            "2. View all contacts\n",
            "3. Search contact\n",
            "4. Update contact\n",
            "5. Delete contact\n",
            "6. Exit\n",
            "Choose an option (1-6): 1\n",
            "Enter name: Vansh\n",
            "Enter phone number: 678904321\n",
            "Enter email: Vansh678@gmail.com\n",
            "Enter address: Bari bhraman, jammu \n",
            "Contact added successfully!\n",
            "\n",
            "===== CONTACT BOOK =====\n",
            "1. Add a contact\n",
            "2. View all contacts\n",
            "3. Search contact\n",
            "4. Update contact\n",
            "5. Delete contact\n",
            "6. Exit\n",
            "Choose an option (1-6): 2\n",
            "\n",
            "Your Contacts:\n",
            "1. Raghav - 456379876\n",
            "2. Vansh - 678904321\n",
            "\n",
            "===== CONTACT BOOK =====\n",
            "1. Add a contact\n",
            "2. View all contacts\n",
            "3. Search contact\n",
            "4. Update contact\n",
            "5. Delete contact\n",
            "6. Exit\n",
            "Choose an option (1-6): 3\n",
            "Enter name or phone number to search: Raghav \n",
            "\n",
            "Name: Raghav\n",
            "Phone: 456379876\n",
            "Email: Raghav876@gmail.com\n",
            "Address: Kali road, delhi\n",
            "\n",
            "===== CONTACT BOOK =====\n",
            "1. Add a contact\n",
            "2. View all contacts\n",
            "3. Search contact\n",
            "4. Update contact\n",
            "5. Delete contact\n",
            "6. Exit\n",
            "Choose an option (1-6): 4\n",
            "\n",
            "Your Contacts:\n",
            "1. Raghav - 456379876\n",
            "2. Vansh - 678904321\n",
            "Enter contact number to update: 678904321\n",
            "Invalid contact number.\n",
            "\n",
            "===== CONTACT BOOK =====\n",
            "1. Add a contact\n",
            "2. View all contacts\n",
            "3. Search contact\n",
            "4. Update contact\n",
            "5. Delete contact\n",
            "6. Exit\n",
            "Choose an option (1-6): 6\n",
            "Goodbye! Your contacts are saved.\n"
          ]
        }
      ]
    }
  ]
}